routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('books','BookController');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    //
    protected $fillable=[
    	'title','description'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
use Session;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //traer todos los libros de la bd
        $books=Book::paginate(3);//permite hacer un menu en la parte de abajo de la pagina con index.blade.php en {{$books->links()}}

//order by permite organizar $books=Book::orderBy('id','DESC')->paginate(3);//
        return view('books.index',compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('books.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //primero se valida si llega informacion
        $request->validate([
'title'=>'required',
'description'=>'required'
        ]);

        Book::create($request->all());

        Session::flash('message','Libro creado');//No realiza el mensaje
        return redirect()->route('books.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
        return view('books.show',compact('book'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
        return view('books.edit',compact('book'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
         $request->validate([
'title'=>'required',
'description'=>'required'
        ]);

$book->update($request->all());

Session::flash('message','Libro actualizado');//No realiza el mensaje
        return redirect()->route('books.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy(Book $book)
    {
        //
        $book->delete();
        Session::flash('message','Libro eliminado correctamente');
       return redirect()->route('books.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

resources/views/books/create.blade.php
@extends('books.layout')

@section('content')

<h1 class="text-center">Crear</h1>
<div class="container">
<form action="{{route('books.store')}}" method="POST">
	@csrf

	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<strong>Titulo:</strong>
				<input type="text" name="title" class="form-control" placeholder="Titulo del libro">
			</div>
		</div>

	<div class="col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				<textarea class="form-control" name="description" placeholder="Descripcion"></textarea>
			</div>
		</div>

<div class="col-md-12 text-center">
	<button type="submit" class="btn btn-primary">Enviar</button>
</div>

	</div>




</form>
</div>
@endsection

resources/views/books/edit.blade.php
@extends('books.layout')

@section('content')

<h1 class="text-center">Crear</h1>
<div class="container">
<form action="{{route('books.update',$book->id)}}" method="POST">
	@csrf
@method('PUT')
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<strong>Titulo:</strong>
				<input type="text" name="title" value="{{$book->title}}" class="form-control" placeholder="Titulo del libro">
			</div>
		</div>

	<div class="col-md-12">
			<div class="form-group">
				<strong>Descripcion:</strong>
				<textarea class="form-control" name="description" placeholder="Descripcion">{{$book->description}}</textarea>
			</div>
		</div>

<div class="col-md-12 text-center">
	<button type="submit" class="btn btn-primary">Enviar</button>
</div>

	</div>




</form>
</div>
@endsection

resources/views/books/index.blade.php
@extends('books.layout')

@section('content')

<h1 class="text-center">Libros</h1>

<div class="container">
	
<a class="btn btn-info mb-3" href="{{route('books.create')}}">Agregar libro</a>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  	@foreach($books as $book)
    <tr>
      <th scope="row">{{ $book->id }}</th>
      <td><a href="{{route('books.show',$book->id)}}">{{ $book->title }}</a></td>
      <td>{{ $book->description }}</td>
      <td><a class="btn btn-info" href="{{route('books.edit',$book->id)}}"><i class="fas fa-edit"></i></a>
      
      <!--Formulario de seguridad para eliminar-->
      <form action="{{route('books.destroy',$book->id)}}" method="POST">
      	@csrf
      	@method('DELETE')
      	<button type="submit" class="btn-sm btn-danger" onclick="return confirm('¿Quiere borrar el elemento?')"><i class="fas fa-trash-alt fa-2x"></i></button>
      </form>
      </td>
    </tr>
    @endforeach
  </tbody>
</table>


{{$books->links()}}

</div>
@endsection

resources/views/books/layout.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<!--Agregar css desde public-->
<link rel="stylesheet" href="{{asset('css/styles.css')}}">

<!--Fuentes-->
<link href="https://fonts.googleapis.com/css?family=Anton" rel="stylesheet">

<!-- Iconos-->
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <title>Books</title>
  </head>
  <body>


<nav class="navbar navbar-expand-lg navbar-light bg-custom">
  <a class="navbar-brand ebook" href="{{route('books.index')}}">EBooks</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{{route('books.index')}}">Inicio<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
  </div>
</nav>

    @yield('content')
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/books/show.blade.php
@extends('books.layout')

@section('content')

<div class="container">

<div class="card">
  <div class="card-header">
    <h2>{{$book->title}}</h2>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{$book->description}}</p>
      <footer class="blockquote-footer">{{$book->created_at}}</footer>
    </blockquote>
  </div>
</div>

</div>
@endsection